
version: "3.9"

services:
  web:
    build: .
    ports:
      - "8010:8010"
    environment:
      - FLASK_APP=manage.py
      - CONFIG_ENV=dev
      - FLASK_RUN_PORT=8010
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app  # Mount your application directory as a volume
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  postgres_data: {}
